version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # 忽略 JavaFX 依赖的自动更新
      - dependency-name: "org.openjfx:javafx-controls"
      - dependency-name: "org.openjfx:javafx-graphics"
      - dependency-name: "org.openjfx:javafx-base"